# **Tensors in Pytorch**
A tensor is a container for data that can exist in any number of dimensions.

Think of it as a generalization of:

- **Scalar (0D tensor):** A single number (e.g., 5)
- **Vector (1D tensor):** A list of numbers (e.g., [1, 2, 3])
- **Matrix (2D tensor):** A table of numbers (e.g., a spreadsheet)
- **3D Tensor:** A cube of numbers (e.g., a color image: height × width × RGB channels)
- **4D+ Tensor:** A batch of images, or videos (time × height × width × channels)

In [3]:
import torch
V_data = [1, 2, 3, 4, 5]
V = torch.tensor(V_data)
print(V)

tensor([1, 2, 3, 4, 5])


#### **Can also create a tensor of random data with a given dimensionality like:**

In [35]:
x = torch.tensor([1.0, 2.0, 3.0])
print('1D Tensor: \n', x)
print(" ")
y = torch.zeros((3, 3))
print('2D Tensor: \n', y)

1D Tensor: 
 tensor([1., 2., 3.])
 
2D Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5698,  1.3438, -0.5749, -2.0089,  0.1856],
         [-0.7872, -1.4661, -1.0266,  0.5229,  0.2606],
         [-0.0833, -0.2988,  0.6767, -1.2688, -0.0996],
         [ 0.7935, -1.2030, -1.4177,  0.3915, -0.0046]],

        [[ 0.1275, -0.2233,  1.6545, -0.9962, -1.9893],
         [-1.3162, -0.4315, -0.6756, -0.6698, -1.2456],
         [-0.1380,  1.0456,  1.7997,  0.1130, -1.8067],
         [ 0.5921,  1.5770,  1.5628, -0.1317,  0.5708]],

        [[ 0.9636,  1.8604,  0.4624, -0.8676, -1.3758],
         [-0.9187, -0.6208, -1.1647, -0.8759,  0.2955],
         [ 1.4276,  0.9900,  0.5671,  0.6511,  1.4430],
         [-0.2702,  3.1053, -0.4128, -0.0622, -0.0385]]])


#### **torch.zeros():** Creates a new Tensor with all elements, initialized as zeros.
#### **torch.ones():**  Creates a new Tensor with all elements, initialized as ones.

In [31]:
y= torch.zeros([3,3])
print(y)
print(" ")
z = torch.ones([3,3])
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


#### **torch.full()** and **torch.full_like():**  These functions return a Tensor of the required size filled with required fill_value provided. 

In [30]:
newTensor= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newTensor)
print(" ")
x = torch.full_like(newTensor,3.24, dtype=None )
print(x)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])
 
tensor([[3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400]])


### **Tensor attributes:**

Each tensor( torch.Tensor ) has a torch.dtype, torch.device, and torch.layout attributes. 

- **torch.dtype:** A torch.dtype is an object that represents the data type of torch.Tensor. PyTorch has twelve different data types.
- **torch.device:** A torch.device is an object representing the device on which a torch.Tensor is or will be allocated. The torch.device contains a device type ('cpu' or 'cuda') and an optional device ordinal for the device type.

In [9]:
torch.device('cuda:0')

device(type='cuda', index=0)

#### **1. torch.strided:**
The standard, dense tensor layout that PyTorch uses by default. Data is stored in a contiguous block of memory, and strides tell you how many bytes to skip to go to the next element along each dimension.

In [10]:
x = torch.Tensor([[1, 2, 3, 4], [5, 7, 8, 9]])
x.stride()

(4, 1)

#### **2. torch.sparse_coo_tensor (COO = Coordinate List Format)**

A sparse tensor that only stores non-zero elements and their indices. Ideal when most elements are zero (e.g., graphs, one-hot encodings, adjacency matrices).

In [12]:
i = [[0, 1, 1],
     [2, 0, 2]]

v =  [3, 4, 5]
s = torch.sparse_coo_tensor(i, v, (2, 3))
print(s)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)


In [13]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


#### **torch.cat() :** Concatenates a list of tensors

In [29]:
x_1 = torch.randn(2, 3)
y_1 = torch.randn(3, 3)
z_1 = torch.cat([x_1, y_1])
print(x_1)
print(" ")
print(y_1)
print(" ")
print(z_1)

tensor([[ 0.4592,  1.5375, -0.2147],
        [ 2.0285,  1.2308,  0.2423]])
 
tensor([[ 0.3073, -1.4227, -0.3776],
        [-0.4997, -0.9968, -2.6500],
        [-0.8469,  0.5835,  1.1328]])
 
tensor([[ 0.4592,  1.5375, -0.2147],
        [ 2.0285,  1.2308,  0.2423],
        [ 0.3073, -1.4227, -0.3776],
        [-0.4997, -0.9968, -2.6500],
        [-0.8469,  0.5835,  1.1328]])


In [27]:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
z_2 = torch.cat([x_2, y_2], 1)
print(x_2)
print(" ")
print(y_2)
print(" ")
print(z_2)

tensor([[ 0.9789, -0.6421,  0.1694],
        [-0.6260, -0.0617, -0.1880]])
 
tensor([[ 0.4374, -2.1160, -0.2150, -0.1752,  0.4373],
        [ 0.8545,  2.0512,  0.5119, -0.3952, -0.3734]])
 
tensor([[ 0.9789, -0.6421,  0.1694,  0.4374, -2.1160, -0.2150, -0.1752,  0.4373],
        [-0.6260, -0.0617, -0.1880,  0.8545,  2.0512,  0.5119, -0.3952, -0.3734]])


#### **view():** You can reshape tensors using the .view() method as shown below.

In [25]:
x = torch.randn(2, 2, 3)
print(x)
print(" ")
print(x.view(2, 6))

tensor([[[-0.8498, -1.0202,  1.5617],
         [-1.1000,  1.1125,  1.5885]],

        [[ 0.8708, -1.3895,  0.7623],
         [ 0.8764, -1.3785, -0.5999]]])
 
tensor([[-0.8498, -1.0202,  1.5617, -1.1000,  1.1125,  1.5885],
        [ 0.8708, -1.3895,  0.7623,  0.8764, -1.3785, -0.5999]])


#### **Reshaping and Transposing Tensors**

In [36]:
t = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Reshaping")
print(t.reshape(6, 2))

print("\nResizing")
print(t.view(2, 6))

print("\nTransposing")
print(t.transpose(0, 1))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


#### **torch.argmax():** Returns the index of the maximum value of all elements in the input tensor.

In [32]:
x = torch.randn(3,3)
print((x, torch.argmax(x)))

(tensor([[-1.1142, -0.6312,  1.5615],
        [-0.6982,  0.2584,  0.5807],
        [-0.9396, -0.2951, -1.6126]]), tensor(2))


#### **torch.argmin():** Similar to argmax(), it returns the minimum value of all elements in the input tensor.

In [33]:
x = torch.randn(3,3)
print((x, torch.argmin(x)))

(tensor([[ 0.4202, -1.9865,  1.1275],
        [-0.6350,  0.0802, -0.4745],
        [-0.5234,  2.0170, -1.5258]]), tensor(1))
